name: Deepin-Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  APP_NAME: deepin
  DOCKERHUB_REPO: vscwjm/deepin

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deepin-docker
      run: docker build . --file Dockerfile --tag deepin-docker:$(date +%s)
